
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: dantech-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dantech
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  prisma-migrate:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: sh -c "npm install && npx prisma db push && npx prisma generate"


  redis:
    image: redis:7.2-alpine
    container_name: dantech-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

