
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: dantech-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dantech
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dantech"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - dantech-network

  prisma-migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migration
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dantech?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dantech-network


  redis:
    image: redis:7.2-alpine
    container_name: dantech-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - dantech-network

  
  dantech-server:
    container_name: dantech-server
    build:
      context: .     
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dantech?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      prisma-migrate:
        condition: service_completed_successfully
    ports:
      - "5000:5000"
    init: true
    restart: unless-stopped
    networks:
      - dantech-network

networks:
  dantech-network:
    name: dantech-network
